### ISSUE TITLE
MethodError when saving ingredient array to database

### ISSUE THREAD

**Issue by maryhipp** [maryhipp/mycookbook#2]
User story: User can save recipes from search to their Cookbook

Error: NoMethodError in RecipesController#create; undefined method `[]' for nil:NilClass

error arises when attempting to iterate through JSON to grab ingredients and save them into database as array; works when exact same method is used to display ingredients in search page
Already attempted:

Troubleshooting in pry...works in pry!
Adding "serialize :ingredients" to recipe model
Hours spent researching last night and can't find solution

**Comment by peterylai** [comment]
Duplicate of other issue. Closing.
